FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./amqp_lib.py ./invokes.py ./manage_deliveries.py .env serviceAccountKey.json ./
CMD [ "python", "./manage_deliveries.py" ]
